# Generated by Django 4.2 on 2023-04-30 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(verbose_name='site_url')),
                ('site_name', models.CharField(max_length=50, verbose_name='site_name')),
                ('username', models.CharField(max_length=200, verbose_name='username')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_date_edited', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
